language: php
cache:
  directories:
    - $HOME/.composer/cache
    - .php_cs
jobs:
  include:
    - stage: test
      php: 7.3
      env: PREFER_LOWEST=""
      before_script:
        - &composerupdate
          composer update --prefer-dist $PREFER_LOWEST
      script:
        - &phpunit
          "./vendor/bin/phpunit"
        - composer phpstan
        - composer cs-check
      after_script:
        - travis_retry php vendor/bin/php-coveralls -v
    - stage: test
      php: 7.4
      env: PREFER_LOWEST=""
      before_script:
        - *composerupdate
      script:
        - *phpunit
    - stage: test
      php: 7.2
      env: PREFER_LOWEST=""
      before_script:
        - *composerupdate
      script:
        - *phpunit
    - stage: test
      php: 7.2
      env: PREFER_LOWEST="--prefer-lowest"
      before_script:
        - *composerupdate
      script:
        - *phpunit
    # Test bundle
    - stage: test_dependencies
      php: 7.3
      env: PREFER_LOWEST=""
      before_script:
        - mkdir -p tests/dependencies
        - rsync -av . tests/dependencies/copy/ --exclude tests --exclude vendor
        - cd tests/dependencies
        - git clone https://github.com/thecodingmachine/graphqlite-bundle.git
        - php ./makeComposerLocal.php graphqlite-bundle/composer.json
        - cd graphqlite-bundle
        - composer install
      script:
        - vendor/bin/phpunit
    # Test graphqlite-universal-service-provider
    - stage: test_dependencies
      php: 7.3
      env: PREFER_LOWEST=""
      before_script:
        - mkdir -p tests/dependencies
        - rsync -av . tests/dependencies/copy/ --exclude tests --exclude vendor
        - cd tests/dependencies
        - git clone https://github.com/thecodingmachine/graphqlite-universal-service-provider.git
        - php ./makeComposerLocal.php graphqlite-universal-service-provider/composer.json
        - cd graphqlite-universal-service-provider
        - composer install
      script:
        - vendor/bin/phpunit
    # Test graphqlite-laravel
    - stage: test_dependencies
      php: 7.3
      env: PREFER_LOWEST=""
      before_script:
        - mkdir -p tests/dependencies
        - rsync -av . tests/dependencies/copy/ --exclude tests --exclude vendor
        - cd tests/dependencies
        - git clone https://github.com/thecodingmachine/graphqlite-laravel.git
        - php ./makeComposerLocal.php graphqlite-laravel/composer.json
        - cd graphqlite-laravel
        - composer install
      script:
        - vendor/bin/phpunit
    - stage: doc
      if: branch = master AND type = push
      name: "Doc generation"
      language: node_js
      node_js: 8
      cache:
        yarn: true
      script:
        - git config --global user.name "${GH_NAME}"
        - git config --global user.email "${GH_EMAIL}"
        - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        - cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages
matrix:
  allow_failures:
    - stage: test_dependencies
