# Generate the complete documentation then upload to the website under the master section
name: "Doc generation"

on:
  pull_request: ~
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:

  doc-generation:

    name: "Doc generation"
    runs-on: "ubuntu-latest"
    steps:

      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Setup NodeJS"
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14.x'

      - name: "Yarn install"
        run: yarn install
        working-directory: "website"

      - name: "Yarn build"
        run: yarn run build
        working-directory: "website"

      - name: "Deploy website"
        if: "${{ github.event_name == 'push' || github.event_name == 'release' }}"
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: website/build # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch
