# Generate the complete documentation then upload to the website under the master section
name: "Doc generation on master"

on:
  push:
    branches:
      - master

jobs:

  doc-generation:

    name: "Doc generation"
    runs-on: "ubuntu-latest"
    steps:

      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Setup NodeJS"
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

#      - name: "Update git config"
#        run: git config --global user.name "${GH_NAME}" && git config --global user.email "${GH_EMAIL}" && echo "machine github.com login ${GH_NAME} password ${GITHUB_TOKEN}" > ~/.netrc

      - name: "Yarn install"
        run: yarn install
        working-directory: "website"

#      - name: "Push the new doc"
#        run: GIT_USER="${{ github.actor }}" yarn run publish-gh-pages
#        working-directory: "website"

      - name: "Yarn build"
        run: yarn run build
        working-directory: "website"

      - name: "Deploy website"
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: website/build/graphqlite # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
